# This file was generated by GoReleaser. DO NOT EDIT.
class Compass < Formula
  desc ""
  homepage ""
  version "4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/khoi/compass/releases/download/4/compass_4_darwin_amd64.tar.gz"
    sha256 "13edec304ecd5bf629f04f9f25e42b9cdb8768425f985fd07dd3c3ca1f51db0d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/khoi/compass/releases/download/4/compass_4_linux_amd64.tar.gz"
      sha256 "6c8738234a50b0ef9f32d840a749287d07f3fcb3132a70635a3ce345d9fa3bb6"
    end
  end

  def install
    bin.install "compass"
  end

  test do
    system "#{bin}/program -h"
  end
end
