# This file was generated by GoReleaser. DO NOT EDIT.
class Compass < Formula
  desc ""
  homepage ""
  version "5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/khoi/compass/releases/download/5/compass_5_darwin_amd64.tar.gz"
    sha256 "1692cdd400584e92f19ee8abce29931e755cc7e485876453a54961f17e08d727"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/khoi/compass/releases/download/5/compass_5_linux_amd64.tar.gz"
      sha256 "98a9336a0755fe75c2e5c522b798e6b20fb9fee35aed38d5fbf1139418766963"
    end
  end

  def install
    bin.install "compass"
  end

  test do
    system "#{bin}/program -h"
  end
end
