# This file was generated by GoReleaser. DO NOT EDIT.
class Gdupes < Formula
  desc "🧹 gdupes - find duplicate file"
  homepage "https://github.com/khoi/gdupes"
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/khoi/gdupes/releases/download/0.1/gdupes_0.1_darwin_amd64.tar.gz"
    sha256 "ba2bb4f6298e719fed162b2417a2a1f419e70aa9b61f2e8fb8aab8918c6446dc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/khoi/gdupes/releases/download/0.1/gdupes_0.1_linux_amd64.tar.gz"
      sha256 "298a977af86aff287a1bcb7dde813dfca0db810edd5a102a929c5c7011dcd0aa"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/khoi/gdupes/releases/download/0.1/gdupes_0.1_linux_arm64.tar.gz"
        sha256 "4ef80281162a52a279256d01a50f36900c121f402b982191f7a3a4c43bebee5d"
      else
        url "https://github.com/khoi/gdupes/releases/download/0.1/gdupes_0.1_linux_armv6.tar.gz"
        sha256 "f7b38b21b28c4595d47605f6177c37cc4f6c18799ae2fea6c02fc0f63e5fe9b8"
      end
    end
  end

  def install
    bin.install "gdupes"
  end

  test do
    system "#{bin}/gdupes ./"
  end
end
